// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkcYHZWDb8JfTqN2qh_oe4zM1zeOUFTHQ',
    appId: '1:124775862833:web:6e785757329ab32094bb10',
    messagingSenderId: '124775862833',
    projectId: 'store-product-b08fa',
    authDomain: 'store-product-b08fa.firebaseapp.com',
    storageBucket: 'store-product-b08fa.firebasestorage.app',
    measurementId: 'G-GE0CG5YXBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAONosJVnmmsbBC-lMvygoBlvTyy7nPZIA',
    appId: '1:124775862833:android:7b10f389b46a156194bb10',
    messagingSenderId: '124775862833',
    projectId: 'store-product-b08fa',
    storageBucket: 'store-product-b08fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhU2S0ds8cfjPXwpeFKIfjSrP7f_RgeY',
    appId: '1:124775862833:ios:a78f9b95f9ddd86294bb10',
    messagingSenderId: '124775862833',
    projectId: 'store-product-b08fa',
    storageBucket: 'store-product-b08fa.firebasestorage.app',
    iosBundleId: 'com.example.storeProducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhU2S0ds8cfjPXwpeFKIfjSrP7f_RgeY',
    appId: '1:124775862833:ios:a78f9b95f9ddd86294bb10',
    messagingSenderId: '124775862833',
    projectId: 'store-product-b08fa',
    storageBucket: 'store-product-b08fa.firebasestorage.app',
    iosBundleId: 'com.example.storeProducts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkcYHZWDb8JfTqN2qh_oe4zM1zeOUFTHQ',
    appId: '1:124775862833:web:16f7dc5c332f25c794bb10',
    messagingSenderId: '124775862833',
    projectId: 'store-product-b08fa',
    authDomain: 'store-product-b08fa.firebaseapp.com',
    storageBucket: 'store-product-b08fa.firebasestorage.app',
    measurementId: 'G-HE48BXMC03',
  );
}
